version: '3'
services:
  fluentd:
    image: ${DOCKER_LOGIN}/fluentd
    container_name: fluentd
    hostname: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.4.0
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
