version: '3'
services:
  fluentd:
    image: ${DOCKER_LOGIN}/fluentd:latest
    container_name: fluentd
    hostname: fluentd
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.16.3
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

networks:
  front_net:
  back_net:
