version: '3.3'
services:
  post_db:
    container_name: post_db
    hostname: post_db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    container_name: ui
    hostname: ui
    image: ${DOCKER_LOGIN}/ui:${UI_VERSION}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  post:
    container_name: post
    hostname: post
    image: ${DOCKER_LOGIN}/post:${POST_VERSION}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    networks:
      - front_net
      - back_net

    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    container_name: comment
    hostname: comment
    image: ${DOCKER_LOGIN}/comment:${COMMENT_VERSION}
    networks:
      - front_net
      - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: ${DOCKER_LOGIN}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net
  node-exporter:
    container_name: node-exporter
    hostname: node-exporter
    image: prom/node-exporter:v1.3.1
    # user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
  mongodb_exporter:
    container_name: mongodb_exporter
    hostname: mongodb_exporter
    image: percona/mongodb_exporter:0.34.0
    ports:
      - 9216:9216
      - 17001:17001
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      - back_net
volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    driver: bridge
    driver_opts:
      subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    driver_opts:
      subnet: 10.0.2.0/24
