---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: reddit
    component: ui
spec:
  type: NodePort
  selector:
      app: reddit
      component: ui
  ports:
  - port: 9292
    nodePort: 32092
    protocol: TCP
    targetPort: 9292

