version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${DOCKER_LOGIN}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${DOCKER_LOGIN}/post:${POST_VERSION}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${DOCKER_LOGIN}/comment:${COMMENT_VERSION}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    driver_opts:
      subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    driver_opts:
      subnet: 10.0.2.0/24
